### ISSUE TITLE
Securing Your Clusters - iap-ingress privateGKECluster parameter config

### ISSUE THREAD

**Issue by anifort** [kubeflow/website#1884] opened 2020-04-08 11:44 UTC
https://www.kubeflow.org/docs/gke/private-clusters/

The following instructions are wrong as the structure is not different. There is no iap-ingress.yaml and also I cannot find the privateGKECluster parameter in iap-ingress/kustomization.yaml (on any yaml within the iap-ingress directory)

>Update iap-ingress component parameters:
>```
>cd ${KF_DIR}/kustomize
>gvim iap-ingress.yaml
>```
>Find and set the privateGKECluster parameter to true:
>```
>privateGKECluster: "true"
>```
>Then apply your changes:
>```
>kubectl apply -f iap-ingress.yaml
>```

**Comment by jlewi** [comment] 2020-04-08 14:34
Duplicate of #1881

**Closed by jlewi** 2020-04-08 14:34 UTC
Labels: kind/bug, platform/gcp, priority/p1
