### ISSUE TITLE
please provide a working installation guide

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/website#1570] opened 2020-01-29 09:31 UTC
Please provide a working setup guide (ubuntu 18.04 lts)

I've tried several instructions provided on your page. Only GCP does fully work. The following instructions do not work on Ubuntu 18.04 LTS

https://www.kubeflow.org/docs/started/workstation/getting-started-linux/
-> microk8s Version
-> MiniKF
-> Workstation

There are multiple problems, from kustomize bugs to certification errors (already referenced in different other issues)

A working microk8s installation would be great for kubeflow 0.7.1 (or 0.7.0)

kfctl v0.7.1-2-g55f9b2a
microk8s.kubectl v1.14.10
kfctl_existing_arrikto.0.7.1.yaml and/or kfctl_k8s_istio.0.7.1.yaml

follow docs at: 
https://www.kubeflow.org/docs/started/workstation/getting-started-linux/#linux-server
then https://www.kubeflow.org/docs/started/k8s/overview/
then https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/
```sudo -i
snap install microk8s --classic --channel=1.14/stable
#export PATH=$PATH:/snap/bin
snap alias microk8s.kubectl kubectl
which kubectl
kubectl version —> GitVersion:"v1.14.10"
# workaround because of kustomize error
wget https://github.com/kubeflow/kubeflow/releases/download/v0.7.1/kfctl_v0.7.1-2-g55f9b2a_linux.tar.gz
tar -xvf kfctl_v0.7.1-2-g55f9b2a_linux.tar.gz
# end workaround because of kustomize error
export PATH=$PATH:$(pwd)
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/b37bad9eded2c47c54ce1150eb9e6edbfb47ceda/kfdef/kfctl_existing_arrikto.0.7.1.yaml"
export KF_NAME=kubeflow-poc
export BASE_DIR=/root/kubeflow
export KF_DIR=${BASE_DIR}/${KF_NAME}
mkdir -p ${KF_DIR}
export KF_INST=${BASE_DIR}/kubeflow-inst
mkdir -p ${KF_DIR}
cd ${KF_INST}
wget $CONFIG_URI
wget uri: https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz
tar -xvf v0.7-branch.tar.gz
# workaround because of kustomize error
vi kfctl_existing_arrikto.0.7.1.yaml
uri: https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz --> /root/kubeflow/kubeflow-poc/manifests-0.7-branch
# end workaround because of kustomize error
export CONFIG_FILE=${KF_DIR}/kfctl_existing_arrikto.0.7.1.yaml
# admin@kubeflow.org / Password is "12341234", 12-round bcrypt-hashed.
kfctl apply -V -f ${CONFIG_FILE}

Output:

...
INFO[0091] Applied the configuration Successfully!       filename="cmd/apply.go:72"

```

Update: I was able to deploy kubeflow on microk8s now (some old leftovers caused weird behaviors). 

- But still: how do I get the port / url to connect to the webgui?
- How do I expose the port, so other clients can access the gui from their desktops?

**Comment by jlewi** [comment] 2020-02-06 18:32
@ammarn911 recently updated the docs for MicroK8s

#1113 is tracking fixing the MicroK8s guide.

So I'm going to close this as a duplicate of that issue.

Duplicate of #1113

**Closed by jlewi** 2020-02-06 18:32 UTC
Labels: doc-sprint, kind/bug, platform/microk8s, priority/p2
