### ISSUE TITLE
Add a quickstart for Minikube deployment

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/website#229] opened 2018-09-17 17:23 UTC
A quickstart describing how to use setup-minikube.sh.

**Comment by jlewi** [comment] 2018-10-01 13:21
We have instructions here:
https://www.kubeflow.org/docs/started/getting-started-minikube/

**Comment by jlewi** [comment] 2018-10-01 13:22
Duplicate of #231 (get rid of bootstrapper in docs)

**Closed by jlewi** 2018-10-01 13:22 UTC
Labels: area/0.3.0, area/docs, priority/p1
