### ISSUE TITLE
AWS: Authentication and TLS Support

### ISSUE THREAD

**Issue by charlesparasa** [kubeflow/website#1541] opened 2020-01-20 16:12 UTC
https://www.kubeflow.org/docs/aws/authentication/

Aws does not provide with ARN for the custom domain has the auth.us-east-1.amazoncognito.com belongs to AWS and the document does not say how to configure the Custom Domain ARN.

And the cognitoUserPoolDomain : field parameter is confusing. domain/your-pool-name
for eaxmple : kubeflow.example.com/kubeflow (our pool name)

**Comment by Jeffwan** [comment] 2020-02-11 19:56
`cognitoUserPoolDomain` is the cognito pool name. `Custom Domain ARN` will be addressed in #1435

**Comment by Jeffwan** [comment] 2020-02-12 00:18
@charlesparasa Can you check if #1661 is clear enough for you?

**Comment by Jeffwan** [comment] 2020-02-23 20:03
This has been address in #1661 and it's also a duplicate of #1435. I think we can close this one and track in #1435 

/close

**Closed by Jeffwan** 2020-02-23 20:03 UTC
Labels: kind/feature
