### ISSUE TITLE
KSonnet being archived / Kubeflow on Kubernetes

### ISSUE THREAD

**Issue by leafmulch** [kubeflow/website#761] opened 2019-06-03 14:27 UTC
The tool ks is being archived https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware.

**Comment by sarahmaddox** [comment] 2019-06-27 05:13
Thanks for raising this issue! I'm closing it as a duplicate of https://github.com/kubeflow/website/issues/825, which now has more detail.

/close

**Closed by sarahmaddox** 2019-06-27 05:13 UTC
Labels: kind/bug
