### ISSUE TITLE
Tracking Issue - Kubeflow v1.4 docs

### ISSUE THREAD

**Issue by RFMVasconcelos** [kubeflow/website#2879] opened 2021-08-16 16:47 UTC
As we prepare to release Kubeflow v1.4 is it important to make sure documentation is updated accordingly. See [Release Kanban](https://github.com/orgs/kubeflow/projects/46). 

As discussed in the Release team meeting just now, we would ask Working Group leads to use this thread to track updates. 

CC:
@kubeflow/wg-automl-leads 
@kubeflow/wg-manifests-leads 
@kubeflow/wg-notebooks-leads 
@kubeflow/wg-pipeline-leads 
@kubeflow/wg-training-leads 
@kubeflow/kfserving-owners 

Soon, a `v1.3-branch` branch has to be created in order to freeze `v1.3` specific docs, and documentation pointed to that branch in order to allow `v1.4` specific docs not to be in production until the release date - as per [release guidelines](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#version-the-website). 

Track release issues in the [Release Kanban](https://github.com/orgs/kubeflow/projects/46), and the [Docs Kanban](https://github.com/orgs/kubeflow/projects/45).

cc @kimwnasptd @mkbhanda @knkski @jbottum @thesuperzapper @Arhell @Bobgy @joeliedtke @DavidSpek

**Comment by kimwnasptd** [comment] 2021-08-25 08:50
Thanks for starting this @RFMVasconcelos! 

From my side I'll be working this week on updating the Katib docs to use the new Katib UI https://github.com/kubeflow/katib/issues/1595

cc @kubeflow/wg-automl-leads

**Comment by kimwnasptd** [comment] 2021-08-25 09:57
For Notebooks WG I'll be working on updating the CentralDashboard docs https://github.com/kubeflow/website/issues/2892.

@thesuperzapper @DavidSpek will you work on updating the docs about the Notebook servers for 1.4, since you are the main developers of that component?

**Comment by nakfour** [comment] 2021-09-14 14:10
We have two documentation PR, not specifically for 1.4
https://github.com/kubeflow/website/pull/2942
https://github.com/kubeflow/website/pull/2802

**Comment by yhwang** [comment] 2021-09-14 16:12
one PR here: https://github.com/kubeflow/website/pull/2946 to update `Kubeflow on IBM Cloud` distribution doc for kubeflow 1.4

**Comment by Talador12** [comment] 2021-09-22 16:17
Could we add an issue for updating the readme sections?
For instane, Manifests readme has the single line install needs to be confirmed in 1.4 and any edge cases can be noted there. Some of the language is still showing as 1.3.

**Comment by thesuperzapper** [comment] 2021-09-26 22:01
@jbottum as stated in https://github.com/kubeflow/website/pull/2934#issuecomment-927379095, PR https://github.com/kubeflow/website/pull/2934 needs to be reverted.

**Comment by yhwang** [comment] 2021-09-28 19:10
Add one more PR: https://github.com/kubeflow/website/pull/2979 for IBM IKS.

**Comment by yhwang** [comment] 2021-10-04 18:00
I guess it's time to update the kfp version for IKS on `Installing Kubeflow` page: https://github.com/kubeflow/website/pull/2994

**Comment by thesuperzapper** [comment] 2021-10-05 03:11
I think it's worth getting https://github.com/kubeflow/website/issues/2967 resolved. That is, creating a new `"guides"` docs section, and moving the `"distributions"` that are install guides for `kubeflow/manifets` into it.

It shouldn't be a lot of work, and it seems to have broad support in the community as it significantly clarifies how to install kubeflow.

@yhwang this is relevant to your IKS issue.

**Comment by zijianjoy** [comment] 2021-10-05 15:24
Google Cloud distribution doc update: https://github.com/kubeflow/website/pull/2957

**Comment by yhwang** [comment] 2021-10-05 16:16
@thesuperzapper 
> @yhwang this is relevant to your IKS issue.

if you were talking about my comment here: https://github.com/kubeflow/website/issues/2879#issuecomment-933721757
it just updates the version on the `Installing Kubeflow` [page](https://www.kubeflow.org/docs/started/installing-kubeflow/), note related to the guides/distributions.

**Comment by thesuperzapper** [comment] 2021-10-06 02:00
I have made a PR to update the Kubeflow Notebooks docs: https://github.com/kubeflow/website/pull/3003

___NOTE:__ there is still a bit of work for future updates, but its a first step_

**Comment by shannonbradshaw** [comment] 2021-10-06 12:45
Once we cut the 1.4 docs branch, we'll need to update a few pages. I'll track them in this comment:

**Comment by kimwnasptd** [comment] 2021-10-06 12:48
@yhwang @zijianjoy thanks for updating your corresponding distribution docs and the updates!

At this point I'd also like to give a last ping to all WGs to ensure they have merged their docs PRs, or raise any concerns, since we are planning to cut the `v1.4-branch` tomorrow. Of course we can cherry-pick commits later on in the 1.4 branch if something comes up. cc @kubeflow/wg-automl-leads @kubeflow/wg-deployment-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads. You can also :+1: this comment if you are OK.

cc @shannonbradshaw 

> I have made a PR to update the Kubeflow Notebooks docs: #3003
>
> NOTE: there is still a bit of work for future updates, but its a first step

Thank you @thesuperzapper, that's awsome! I'll try my best to review this before the 1.4 deadline, tomorrow, but if I won't make it then we'll have to cherry-pick it next week once I'll have more cycles to review.

**Comment by johnugeorge** [comment] 2021-10-06 18:12
@zijianjoy Can you merge PRs  #2978 #3008  before cutting the new branch?

**Comment by zijianjoy** [comment] 2021-10-06 21:50
@johnugeorge Sounds good, I have approved the two Nutanix PRs. Thanks for making the change!

**Comment by thesuperzapper** [comment] 2021-10-07 02:55
@james-jwu we also need to merge: https://github.com/kubeflow/website/pull/2980

(This reverts a PR which made the docs provide invalid YAML in `Components / Multi Tenancy`.)

**Comment by kimwnasptd** [comment] 2022-01-26 16:12
closing this, since KF 1.4 has been released

/close

**Closed** 2022-01-26 16:12 UTC
