### ISSUE TITLE
what's prescribed for gke kubeflow doesn't work. There is an open bug filed from July 15th. 

### ISSUE THREAD

**Issue by yarcyarc** [kubeflow/website#1243] opened 2019-10-16 13:25 UTC
The recipe and/or url on https://www.kubeflow.org/docs/started/cloud/getting-started-gke/ leading to https://deploy.kubeflow.cloud doesn't work. 

There is a bug filed https://github.com/kubeflow/kubeflow/issues/3659.

**Comment by jlewi** [comment] 2019-10-22 03:23
Duplicate of kubeflow/kubeflow#3659

**Closed by jlewi** 2019-10-22 03:23 UTC
Labels: kind/bug
