### ISSUE TITLE
Update doc for KF notebooks 

### ISSUE THREAD

**Issue by karthikv2k** [kubeflow/website#615] opened 2019-04-08 21:32 UTC
https://www.kubeflow.org/docs/components/jupyter/ seems outdated.

**Comment by sarahmaddox** [comment] 2019-04-09 13:05
Thanks for raising this issue! I'm closing it as a duplicate of this existing issue:
https://github.com/kubeflow/website/issues/561

/close

**Closed by sarahmaddox** 2019-04-09 13:05 UTC
Labels: area/docs, feature_request
