### ISSUE TITLE
WtD Fixit updates to Install Kubeflow

### ISSUE THREAD

**Issue by shimdude** [kubeflow/website#1387] opened 2019-11-14 03:04 UTC
https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/

Fixing heading to sentence case

**Comment by sarahmaddox** [comment] 2019-11-14 05:18
Duplicate of issue https://github.com/kubeflow/website/issues/1360

/close

**Closed by sarahmaddox** 2019-11-14 05:18 UTC
Labels: kind/bug
