### ISSUE TITLE
Minikube deployment error: unable to recognize "default.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by MeisterUrian** [kubeflow/website#998] opened 2019-07-30 10:02 UTC
Get started: https://www.kubeflow.org/docs/started/getting-started-minikube/

after
```bash
${KUBEFLOW_SRC}/scripts/kfctl.sh apply all
```

such output:

```bash
+ ENV_FILE=env.sh
+ SKIP_INIT_PROJECT=false
+ GKE_API_VERSION=v1beta1
+ GCP_DEFAULT_ZONE=us-east1-d
+++ dirname /home/alex/tmp/kubeflow/scripts/kfctl.sh
++ cd /home/alex/tmp/kubeflow/scripts
++ pwd
+ DIR=/home/alex/tmp/kubeflow/scripts
+ source /home/alex/tmp/kubeflow/scripts/util.sh
+ source /home/alex/tmp/kubeflow/scripts/gke/util.sh
++ set -xe
+ source /home/alex/tmp/kubeflow/scripts/azure/util.sh
++ set -xe
+ source /home/alex/tmp/kubeflow/scripts/aws/util.sh
++ set -xe
+ source /home/alex/tmp/kubeflow/scripts/util-minikube.sh
++ RED='\033[0;31m'
++ GREEN='\033[0;32m'
++ YELLOW='\033[0;33m'
++ NC='\033[0m'
++ MOUNT_LOCAL=true
+ INPUT=()
+ FORMAT=()
+ export 'KUBEFLOW_COMPONENTS="ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
+ KUBEFLOW_COMPONENTS='"ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
+ export KUBEFLOW_EXTENDEDINFO=false
+ KUBEFLOW_EXTENDEDINFO=false
+ which envsubst
+ [[ 2 -lt 2 ]]
+ COMMAND=apply
+ WHAT=all
+ shift
+ shift
+ main
+ [[ apply == \i\n\i\t ]]
+ source env.sh
++ PLATFORM=minikube
++ KUBEFLOW_REPO=/home/alex/tmp/kubeflow
++ KUBEFLOW_VERSION=master
++ KUBEFLOW_COMPONENTS='"ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"'
++ KUBEFLOW_EXTENDEDINFO=false
++ KUBEFLOW_KS_DIR=/home/alex/tmp/kubeflow/kfapp/ks_app
++ KUBEFLOW_DOCKER_REGISTRY=
++ DOCKER_REGISTRY_KATIB_NAMESPACE=
++ CLUSTER_ADMIN=alex
++ K8S_NAMESPACE=kubeflow
++ KUBEFLOW_PLATFORM=minikube
++ MOUNT_LOCAL=true
++ DEPLOYMENT_NAME=kfapp
+ [[ -z apply ]]
+ [[ -z all ]]
+ check_installed_deps
+ kf_deps=("ks" "kubectl")
+ declare -a kf_deps
+ kf_dep=ks
+ min_ks_ver=0.11.0
++ ks version
++ cut '-d ' -f3
++ head -1
+ ks_ver=0.13.1
+ '[' 0.13.1 '<' 0.11.0 ']'
+ [[ minikube == \g\c\p ]]
+ [[ minikube == \a\z\u\r\e ]]
+ [[ minikube == \a\w\s ]]
+ [[ apply == \g\e\n\e\r\a\t\e ]]
+ [[ apply == \a\p\p\l\y ]]
+ [[ all == \p\l\a\t\f\o\r\m ]]
+ [[ all == \a\l\l ]]
+ [[ minikube == \g\c\p ]]
+ [[ minikube == \a\z\u\r\e ]]
+ [[ minikube == \a\w\s ]]
+ [[ all == \k\8\s ]]
+ [[ all == \a\l\l ]]
+ ksApply
+ pushd /home/alex/tmp/kubeflow/kfapp/ks_app
~/tmp/kubeflow/kfapp/ks_app ~/tmp/kubeflow/kfapp
+ createNamespace
+ set +e
++ kubectl get namespace kubeflow
+ O='NAME       STATUS    AGE
kubeflow   Active    1d'
+ RESULT=0
+ set -e
+ [[ 0 -eq 0 ]]
+ echo 'namespace kubeflow already exists'
namespace kubeflow already exists
+ createKsEnv
+ pushd /home/alex/tmp/kubeflow/kfapp/ks_app
~/tmp/kubeflow/kfapp/ks_app ~/tmp/kubeflow/kfapp/ks_app ~/tmp/kubeflow/kfapp
+ set +e
++ ks env describe default
+ O='name: default
kubernetesversion: v1.14.1
path: default
destination:
  server: https://192.168.99.104:8443
  namespace: kubeflow
targets: []
libraries: {}'
+ RESULT=0
+ set -e
+ '[' 0 -eq 0 ']'
+ echo environment default already exists
environment default already exists
+ popd
~/tmp/kubeflow/kfapp/ks_app ~/tmp/kubeflow/kfapp
+ [[ minikube != \m\i\n\i\k\u\b\e ]]
+ popd
~/tmp/kubeflow/kfapp
+ [[ minikube == \g\c\p ]]
+ [[ minikube == \a\w\s ]]
+ pushd /home/alex/tmp/kubeflow/kfapp/ks_app
~/tmp/kubeflow/kfapp/ks_app ~/tmp/kubeflow/kfapp
+ ks param set application name kfapp
+ [[ false == true ]]
+ ks param set application components '["ambassador","jupyter","notebook-controller","jupyter-web-app","profiles","centraldashboard","tf-job-operator","pytorch-operator","spartakus","argo","pipeline"]'
+ ks show default -c metacontroller -c application
+ kubectl apply --validate=false -f default.yaml
customresourcedefinition.apiextensions.k8s.io "applications.app.k8s.io" configured
customresourcedefinition.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" configured
customresourcedefinition.apiextensions.k8s.io "controllerrevisions.metacontroller.k8s.io" configured
customresourcedefinition.apiextensions.k8s.io "decoratorcontrollers.metacontroller.k8s.io" configured
customresourcedefinition.apiextensions.k8s.io "notebooks.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "profiles.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "pytorchjobs.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "scheduledworkflows.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "tfjobs.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "viewers.kubeflow.org" configured
customresourcedefinition.apiextensions.k8s.io "workflows.argoproj.io" configured
clusterrole.rbac.authorization.k8s.io "centraldashboard" configured
clusterrole.rbac.authorization.k8s.io "jupyter-web-app-cluster-role" configured
clusterrole.rbac.authorization.k8s.io "notebooks-controller" configured
clusterrole.rbac.authorization.k8s.io "ambassador" configured
clusterrole.rbac.authorization.k8s.io "argo" configured
clusterrole.rbac.authorization.k8s.io "argo-ui" configured
clusterrole.rbac.authorization.k8s.io "ml-pipeline-persistenceagent" configured
clusterrole.rbac.authorization.k8s.io "ml-pipeline-viewer-controller-role" configured
clusterrole.rbac.authorization.k8s.io "pipeline-runner" configured
clusterrole.rbac.authorization.k8s.io "pytorch-operator" configured
clusterrole.rbac.authorization.k8s.io "spartakus" configured
clusterrole.rbac.authorization.k8s.io "tf-job-dashboard" configured
clusterrole.rbac.authorization.k8s.io "tf-job-operator" configured
clusterrolebinding.rbac.authorization.k8s.io "centraldashboard" configured
clusterrolebinding.rbac.authorization.k8s.io "jupyter-web-app-binding" configured
clusterrolebinding.rbac.authorization.k8s.io "meta-controller-cluster-role-binding" configured
clusterrolebinding.rbac.authorization.k8s.io "notebooks-controller" configured
clusterrolebinding.rbac.authorization.k8s.io "profile-controller-cluster-role-binding" configured
clusterrolebinding.rbac.authorization.k8s.io "ambassador" configured
clusterrolebinding.rbac.authorization.k8s.io "argo" configured
clusterrolebinding.rbac.authorization.k8s.io "argo-ui" configured
clusterrolebinding.rbac.authorization.k8s.io "ml-pipeline-persistenceagent" configured
clusterrolebinding.rbac.authorization.k8s.io "ml-pipeline-scheduledworkflow" configured
clusterrolebinding.rbac.authorization.k8s.io "ml-pipeline-viewer-crd-role-binding" configured
clusterrolebinding.rbac.authorization.k8s.io "pipeline-runner" configured
clusterrolebinding.rbac.authorization.k8s.io "pytorch-operator" configured
clusterrolebinding.rbac.authorization.k8s.io "spartakus" configured
clusterrolebinding.rbac.authorization.k8s.io "tf-job-dashboard" configured
clusterrolebinding.rbac.authorization.k8s.io "tf-job-operator" configured
compositecontroller.metacontroller.k8s.io "kfapp-controller" configured
secret "mlpipeline-minio-artifact" unchanged
configmap "jupyter-config" unchanged
configmap "jupyter-web-app-config" unchanged
configmap "kfapp-controller-hooks" unchanged
configmap "workflow-controller-configmap" unchanged
persistentvolumeclaim "minio-pvc" unchanged
persistentvolumeclaim "mysql-pv-claim" unchanged
serviceaccount "ambassador" unchanged
serviceaccount "argo" unchanged
serviceaccount "argo-ui" unchanged
serviceaccount "centraldashboard" unchanged
serviceaccount "default-editor" unchanged
serviceaccount "jupyter" unchanged
serviceaccount "jupyter-notebook" unchanged
serviceaccount "jupyter-web-app" unchanged
serviceaccount "meta-controller-service" unchanged
serviceaccount "ml-pipeline" unchanged
serviceaccount "ml-pipeline-persistenceagent" unchanged
serviceaccount "ml-pipeline-scheduledworkflow" unchanged
serviceaccount "ml-pipeline-ui" unchanged
serviceaccount "ml-pipeline-viewer-crd-service-account" unchanged
serviceaccount "notebook-controller" unchanged
serviceaccount "pipeline-runner" unchanged
serviceaccount "profiles" unchanged
serviceaccount "pytorch-operator" unchanged
serviceaccount "spartakus" unchanged
serviceaccount "tf-job-dashboard" unchanged
serviceaccount "tf-job-operator" unchanged
role.rbac.authorization.k8s.io "profiles" unchanged
role.rbac.authorization.k8s.io "centraldashboard" unchanged
role.rbac.authorization.k8s.io "jupyter-notebook-role" unchanged
role.rbac.authorization.k8s.io "jupyter-role" unchanged
role.rbac.authorization.k8s.io "ml-pipeline" unchanged
role.rbac.authorization.k8s.io "ml-pipeline-scheduledworkflow" unchanged
role.rbac.authorization.k8s.io "ml-pipeline-ui" unchanged
rolebinding.rbac.authorization.k8s.io "profiles" unchanged
rolebinding.rbac.authorization.k8s.io "centraldashboard" unchanged
rolebinding.rbac.authorization.k8s.io "default-editor-role-binding" unchanged
rolebinding.rbac.authorization.k8s.io "jupyter-notebook-role" unchanged
rolebinding.rbac.authorization.k8s.io "jupyter-role" unchanged
rolebinding.rbac.authorization.k8s.io "ml-pipeline" unchanged
rolebinding.rbac.authorization.k8s.io "ml-pipeline-ui" unchanged
service "ambassador" unchanged
service "ambassador-admin" unchanged
service "argo-ui" unchanged
service "centraldashboard" unchanged
service "jupyter-0" unchanged
service "jupyter-lb" unchanged
service "jupyter-web-app" unchanged
service "kfam" unchanged
service "kfapp-controller" unchanged
service "minio-service" unchanged
service "ml-pipeline" unchanged
service "ml-pipeline-tensorboard-ui" unchanged
service "ml-pipeline-ui" unchanged
service "mysql" unchanged
service "notebooks-controller" unchanged
service "pytorch-operator" unchanged
service "tf-job-dashboard" unchanged
service "tf-job-operator" unchanged
deployment.apps "jupyter-web-app" unchanged
deployment.apps "kfam" unchanged
deployment.apps "profiles" unchanged
deployment.apps "ambassador" configured
deployment.apps "kfapp-controller" unchanged
deployment.apps "minio" unchanged
deployment.apps "notebooks-controller" unchanged
deployment.apps "ml-pipeline" unchanged
deployment.apps "ml-pipeline-persistenceagent" unchanged
deployment.apps "ml-pipeline-scheduledworkflow" unchanged
deployment.apps "ml-pipeline-ui" unchanged
deployment.apps "ml-pipeline-viewer-controller-deployment" unchanged
deployment.apps "mysql" unchanged
deployment.extensions "argo-ui" unchanged
deployment.extensions "centraldashboard" unchanged
deployment.extensions "pytorch-operator" unchanged
deployment.extensions "spartakus-volunteer" unchanged
deployment.extensions "tf-job-dashboard" unchanged
deployment.extensions "tf-job-operator" unchanged
deployment.extensions "workflow-controller" unchanged
statefulset.apps "jupyter" unchanged
statefulset.apps "metacontroller" unchanged
application.app.k8s.io "kfapp" configured
error: unable to recognize "default.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```

As result - I have no deployments in minikube dashboard

**Comment by sarahmaddox** [comment] 2019-08-22 02:33
Thanks for reporting this error. The Minikube docs are out of date. A doc update is in progress. Please take a look at this issue for further info, including a quick guide to what the doc should say:
https://github.com/kubeflow/website/issues/1023

**Comment by sarahmaddox** [comment] 2019-08-22 02:34
I'll close this issue, as it's a duplicate of https://github.com/kubeflow/website/issues/1023

/close

**Closed by sarahmaddox** 2019-08-22 02:34 UTC
Labels: kind/bug
