### ISSUE TITLE
"Invitation to our Slack channel" link expires

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/website#312] opened 2018-11-28 00:13 UTC
```This invite link is no longer active.```

Can we automate renew invite link?

**Comment by kunmingg** [comment] 2018-11-28 00:14
@texasmichelle

**Comment by jlewi** [comment] 2018-11-28 02:55
Duplicate of: kubeflow/community#15

**Comment by sarahmaddox** [comment] 2018-11-28 03:00
I'm closing this issue, as it's been marked a duplicate.
/close

**Closed by sarahmaddox** 2018-11-28 03:00 UTC
