### ISSUE TITLE
Add documentation on how to kick off a pipeline via API/CLI/SDK

### ISSUE THREAD

**Issue by aronchick** [kubeflow/website#708] opened 2019-05-15 18:05 UTC
Even if it's just how to generate swagger and create a client from that

**Comment by sarahmaddox** [comment] 2019-06-20 04:08
An update:

* I've created the intro to the Pipelines SDK, which covers the SDK side of things:
https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/

* The Pipelines CLI isn't complete - we've decided not to document it at this stage.

* That leaves just the Pipelines API.

**Comment by sarahmaddox** [comment] 2019-06-20 04:35
I'm going to close this issue, as a duplicate of https://github.com/kubeflow/website/issues/734

/close

**Closed by sarahmaddox** 2019-06-20 04:35 UTC
Labels: improvement/enhancement
