### ISSUE TITLE
[MicroK8s] On "Access Kubeflow" access URL is still correct?

### ISSUE THREAD

**Issue by sakaia** [kubeflow/website#1881] opened 2020-04-08 02:55 UTC
On "Access Kubeflow"
Following document is still correct or it is specific to some version?

> Point browser to either: - http://” Your kubeflow VM IP”:“Ambassador PORT”
> - http://localhost:" Ambassador PORT”

[https://github.com/kubeflow/website/blob/8d1235ef6c312105f2fb0a999e29c4756c3e089f/content/docs/started/workstation/getting-started-multipass.md](https://github.com/kubeflow/website/blob/8d1235ef6c312105f2fb0a999e29c4756c3e089f/content/docs/started/workstation/getting-started-multipass.md)

**Comment by sakaia** [comment] 2020-04-08 04:08
It is also helpful to write AWS case. (not local server)

**Comment by sarahmaddox** [comment] 2020-04-20 03:32
Thanks for reporting this @sakaia! I'm closing this issue as a duplicate of https://github.com/kubeflow/website/issues/1113 
/close

**Closed by sarahmaddox** 2020-04-20 03:32 UTC
Labels: kind/bug
