### ISSUE TITLE
Please update NVIDIA TensorRT Inference Server document for kustomize

### ISSUE THREAD

**Issue by asispatra** [kubeflow/website#1142] opened 2019-09-11 06:02 UTC
Please update [NVIDIA TensorRT Inference Server](https://www.kubeflow.org/docs/components/serving/trtinferenceserver/) document for kustomize. Still the document uses ksonnet.

Thanks.

**Comment by sarahmaddox** [comment] 2019-09-11 06:22
This is a duplicate of https://github.com/kubeflow/website/issues/959

/close

**Closed by sarahmaddox** 2019-09-11 06:22 UTC
Labels: kind/feature

**Comment by asispatra** [comment] 2019-09-11 06:27
@sarahmaddox, Is anyone really working on #959 to update the document? 

Thanks.
